name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Install system dependencies
      run: TERM=dumb sudo apt install libsqlite3-dev -y

    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17
        distribution: temurin

    - name: Clone Flutter SDK
      # We can't do a depth-1 clone, because we need the most recent tag
      # so that Flutter knows its version and sees the constraint in our
      # pubspec is satisfied.  It's uncommon for flutter/flutter to go
      # more than 100 commits between tags.  Fetch 1000 for good measure.
      run: |
        # TODO temp hack 2025-07-08 as Flutter's `main` is broken but `master` works:
        #   https://github.com/zulip/zulip-flutter/pull/1688#issuecomment-3050661097
        #   https://discord.com/channels/608014603317936148/608021351567065092/1392301750383415376
        #   https://github.com/flutter/flutter/issues/171833
        #   (See also "temp hack" items below.)
        git clone --depth=2000 -b master https://github.com/flutter/flutter ~/flutter
        TZ=UTC git --git-dir ~/flutter/.git log -1 --format='%h | %ci | %s' --date=iso8601-local
        echo ~/flutter/bin >> "$GITHUB_PATH"

        # The Flutter tool assumes the tip of tree is "origin/master"
        # (or "upstream/master"):
        #   https://github.com/flutter/flutter/issues/160626
        # TODO(upstream): make workaround unneeded
        # TODO, see temp hack above: git --git-dir ~/flutter/.git update-ref refs/remotes/origin/master origin/main

    - name: Download Flutter SDK artifacts (flutter precache)
      run: flutter precache --universal

    - name: Download our dependencies (flutter pub get)
      run: flutter pub get

    - name: Run tools/check
      # TODO omitting flutter_version, see temp hack above
      run: TERM=dumb tools/check --verbose --all-files analyze test build_runner l10n drift pigeon icons android shellcheck
